SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, TO_CHAR(r.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
    FROM USED_GOODS_BOARD b JOIN USED_GOODS_REPLY r
    ON b.BOARD_ID = r.BOARD_ID
    WHERE TO_CHAR(b.CREATED_DATE, 'YYYY-MM') = '2022-10'
    ORDER BY 6 ASC, 1 ASC;